spring.application.name=civic_fix
spring.web.error.include-message=always

# Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Rest of your configuration...
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


server.port=${PORT:8080}
file.upload-dir=/tmp/uploads/